// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from 'contentful';
import { Document } from '@contentful/rich-text-types';

export interface IAccountFields {
  /** name */
  name?: string | undefined;

  /** id */
  id?: string | undefined;

  /** email */
  email?: string | undefined;

  /** providerId */
  providerId?: string | undefined;
}

export interface IAccount extends Entry<IAccountFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'account';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IAnimationFields {
  /** id */
  id?: string | undefined;

  /** name */
  name?: string | undefined;

  /** scenes */
  scenes?: IScene[] | undefined;
}

export interface IAnimation extends Entry<IAnimationFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'animation';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IAppFields {
  /** type */
  type?: 'app' | 'feature' | 'ui' | 'util' | undefined;

  /** name */
  name: string;

  /** id */
  id: string;
}

export interface IApp extends Entry<IAppFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'app';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IArtistFields {
  /** id */
  id?: string | undefined;

  /** name */
  name?: string | undefined;

  /** profile */
  profile?: IProfile | undefined;

  /** events */
  events?: IEvent[] | undefined;

  /** storefront */
  storefront?: IStorefront | undefined;

  /** members */
  members?: IProfile[] | undefined;

  /** account */
  account?: IAccount | undefined;
}

export interface IArtist extends Entry<IArtistFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'artist';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IEventFields {
  /** name */
  name?: string | undefined;

  /** lineup */
  lineup?: ILineup | undefined;

  /** tickets */
  tickets?: ITicket[] | undefined;

  /** startTime */
  startTime?: string | undefined;

  /** endTime */
  endTime?: string | undefined;

  /** venue */
  venue?: IVenue | undefined;

  /** id */
  id: string;
}

export interface IEvent extends Entry<IEventFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'event';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IFanFields {
  /** id */
  id?: number | undefined;

  /** profile */
  profile?: IProfile | undefined;

  /** name */
  name?: string | undefined;
}

export interface IFan extends Entry<IFanFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'fan';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IFrameFields {
  /** id */
  id?: string | undefined;

  /** iterations */
  iterations?: number | undefined;

  /** height */
  height?: number | undefined;

  /** width */
  width?: number | undefined;

  /** intervals */
  intervals?: number | undefined;

  /** t */
  t?: Record<string, any> | undefined;
}

export interface IFrame extends Entry<IFrameFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'frame';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IKeyframeFields {
  /** id */
  id?: string | undefined;

  /** duration */
  duration?: number | undefined;

  /** properties */
  properties?: Record<string, any> | undefined;

  /** order */
  order?: number | undefined;
}

export interface IKeyframe extends Entry<IKeyframeFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'keyframe';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ILayerFields {
  /** id */
  id?: string | undefined;

  /** order */
  order?: number | undefined;

  /** frames */
  frames?: IFrame[] | undefined;

  /** keyframes */
  keyframes?: IKeyframe[] | undefined;
}

export interface ILayer extends Entry<ILayerFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'layer';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ILineupFields {
  /** id */
  id?: number | undefined;

  /** performances */
  performances?: IPerformance[] | undefined;

  /** event */
  event?: IEvent | undefined;

  /** name */
  name?: string | undefined;
}

export interface ILineup extends Entry<ILineupFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'lineup';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IMessageFields {
  /** id */
  id?: number | undefined;

  /** author */
  author?: IAccount | undefined;

  /** recipient */
  recipient?: IAccount | undefined;

  /** text */
  text?: string | undefined;
}

export interface IMessage extends Entry<IMessageFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'message';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IPerformanceFields {
  /** id */
  id?: number | undefined;

  /** artist */
  artist?: IArtist | undefined;

  /** startTime */
  startTime?: string | undefined;

  /** endTime */
  endTime?: string | undefined;

  /** name */
  name?: string | undefined;
}

export interface IPerformance extends Entry<IPerformanceFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'performance';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IProductFields {
  /** id */
  id?: number | undefined;

  /** name */
  name?: string | undefined;

  /** cost */
  cost?: number | undefined;

  /** price */
  price?: number | undefined;

  /** variants */
  variants?: IProduct[] | undefined;
}

export interface IProduct extends Entry<IProductFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'product';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IProfileFields {
  /** id */
  id?: string | undefined;

  /** name */
  name?: string | undefined;

  /** account */
  account?: IAccount | undefined;

  /** displayName */
  displayName?: string | undefined;

  /** email */
  email?: string | undefined;

  /** phoneNumber */
  phoneNumber?: string | undefined;

  /** photoURL */
  photoURL?: string | undefined;
}

export interface IProfile extends Entry<IProfileFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'profile';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ISceneFields {
  /** id */
  id?: string | undefined;

  /** name */
  name?: string | undefined;

  /** layers */
  layers?: ILayer[] | undefined;
}

export interface IScene extends Entry<ISceneFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'scene';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IScheduleFields {
  /** id */
  id?: number | undefined;

  /** events */
  events?: IEvent[] | undefined;
}

export interface ISchedule extends Entry<IScheduleFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'schedule';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IStorefrontFields {
  /** id */
  id?: number | undefined;

  /** products */
  products?: IProduct[] | undefined;
}

export interface IStorefront extends Entry<IStorefrontFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'storefront';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface ITicketFields {
  /** id */
  id?: number | undefined;

  /** event */
  event?: IEvent | undefined;

  /** cost */
  cost?: number | undefined;

  /** price */
  price?: number | undefined;

  /** qr */
  qr?: Asset | undefined;

  /** account */
  owner?: IAccount | undefined;
}

export interface ITicket extends Entry<ITicketFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'ticket';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export interface IVenueFields {
  /** id */
  id?: number | undefined;

  /** events */
  events?: IEvent[] | undefined;

  /** profile */
  profile?: IProfile | undefined;

  /** storefront */
  storefront?: IStorefront | undefined;

  /** location */
  location?: { lat: number; lon: number } | undefined;

  /** name */
  name?: string | undefined;
}

export interface IVenue extends Entry<IVenueFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: 'venue';
        linkType: 'ContentType';
        type: 'Link';
      };
    };
  };
}

export type CONTENT_TYPE =
  | 'account'
  | 'animation'
  | 'app'
  | 'artist'
  | 'event'
  | 'fan'
  | 'frame'
  | 'keyframe'
  | 'layer'
  | 'lineup'
  | 'message'
  | 'performance'
  | 'product'
  | 'profile'
  | 'scene'
  | 'schedule'
  | 'storefront'
  | 'ticket'
  | 'venue';

export type LOCALE_CODE = 'en-US';

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US';
